### ISSUE TITLE
Allow optional reference to codelist 

### ISSUE THREAD

**Issue by rkottmann** [CenPC434/cius-extension-xml#10]
We think, it would be of advantage to allow referencing the original codelist for which a restriction is defined.

Below is an example of how we did it in the [XML Schema for the cius xml model](https://github.com/CenPC434/cius-extension-xml/blob/adaf8afcfb98159628ee7d67976ee1dd032ce75b/schema/ce-config.xsd#L11). I think not all atrtributes are required. However at minimum we would like to have something like `name`, `listURI` , and `listVersionID`

```xml
  <xs:attributeGroup name="codelistNoListNameAttributeGroup">
    <!-- Shamelessly adopted and adapted from UBL 2.1 -->
    <xs:attribute name="listAgencyID" type="xs:normalizedString" use="optional"/>
    <!-- Shamelessly adopted and adapted from UBL 2.1 -->
    <xs:attribute name="listAgencyName" type="xs:string" use="optional"/>
    <!-- Shamelessly adopted and adapted from UBL 2.1 -->
    <xs:attribute name="listVersionID" type="xs:normalizedString" use="optional"/>
    <!-- Shamelessly adopted and adapted from UBL 2.1 -->
    <xs:attribute name="name" type="xs:string" use="optional"/>
    <!-- Main language of external codelist -->
    <!-- Natural language of xml text content -->
    <!-- According to
    https://www.w3.org/International/questions/qa-when-xmllang.en
    it is NOT recommended to use xml:lang for natural language content of
    external elements. Hence definition of own language attribute. -->
    <xs:attribute name="language" type="xs:normalizedString" use="optional"/>
    <!-- Shamelessly adopted and adapted from UBL 2.1 -->
    <xs:attribute name="listURI" type="xs:anyURI" use="optional"/>
    <!-- Shamelessly adopted and adapted from UBL 2.1 -->
    <xs:attribute name="listSchemeURI" type="xs:anyURI" use="optional"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="codelistRequiredListNameAttributeGroup">
    <xs:attributeGroup ref="c:codelistNoListNameAttributeGroup"/>
    <xs:attribute name="listName" type="xs:string" use="required"/>
</xs:attributeGroup>
```

**Comment by kosek** [comment]
You mean something like
````xml
      <codelist>
          <name>codelist-2</name>
          <listURI>https://example.com/page/containing/description/of/list</listURI>
          <listVersion>2.0.3</listVersion>
          <term>BT-10</term>
          <value>1</value>
          <value>2</value>
          <value>3</value>
          <value>4</value>          
        </codelist>
````
Such elements can be added. Could you provide description of these elements and ideally some real world example so people know what they should put into these attributes?

**Comment by rkottmann** [comment]
Yes, I can provide this. Will work on a merge request.

**Comment by phax** [comment]
What about a link to a GC file - would that be part of the data model?

**Comment by rkottmann** [comment]
> 
> 
> What about a link to a GC file - would that be part of the data model?

Not sure what you mean. One can use listURI to point to a GC= Genericode file.

**Comment by phax** [comment]
Yep sorry. GC = Genericode.
I thougt one link to the "generic website" (e.g. the UNTDID page) and one link to the Genericode files (if available)

**Comment by rkottmann** [comment]
that makes sense to me. good idea. How to name such an elemet? `genericodeURL`? 

But that should be discussed in a new issue, shouldn't it?

**Comment by phax** [comment]
sounds good
