### ISSUE TITLE
Flexibility on Syntax

### ISSUE THREAD

**Issue by phax** [CenPC434/cius-extension-xml#14]
Question: currently we use "UBL" and "CII" as syntax names.
Wouldn't it be good to explicitly add the version so in case we need version updates on the syntaxes, so that we can handle this easily.
Suggestion: replaced `UBL` with `UBL-2.1` and replace `CII` with `CII-D16B`

**Comment by kosek** [comment]
If we anticipate future versions of syntaxes then we should allow any string to appear in the syntax attribute. And suggest using UBL-2.1 and CII-D16B for the current version of syntaxes. Would that work for you?

**Comment by phax** [comment]
Well I would go for an enumeration but just not "UBL" only. So haveing an enum with these 2 values would make sense imho
