### ISSUE TITLE
Add review element

### ISSUE THREAD

**Issue by kosek** [CenPC434/cius-extension-xml#15]
During today's WG meeting it has been agreed to add new optional review element that would contain information about when and how to send feedback during review period.

**Comment by kosek** [comment]
New element could contain embeded HTML markup similarly to other elements. For example:

```` xml
<c:review>
CIUS is currently under the review. You can send your comments until May 30th, 2019 to
email address <a href="mailto:cius-comments@example.com">cius-comments@example.com</a>. 
Alternatively you can log your comments <a href="http://example.com/submit-cius-comment">using 
electronic form</a>.
</c:review>
````

**Comment by phax** [comment]
As long as it is optional.
Would 2 attributes for "startDate" and "endDate" make sense?

**Comment by kosek** [comment]
We can add these attributes, but I would suggest making them optional. I can imagine situations where more review periods will occur and perhaps these two attributes will not be enough to cover all cases.

**Comment by phax** [comment]
Of course optional - the end date is what would be the interesting part (at least that is what I assume)

**Comment by ulrike-linde** [comment]
Fine, thank you! Agree to add "startDate" and "endDate" as two optional elements.
