### ISSUE TITLE
Allow optional reference to genericode url in codelist restriction

### ISSUE THREAD

**Issue by rkottmann** [CenPC434/cius-extension-xml#16]
As disussed in #10 it would be nice to have an optional element e.g. `          <listGenericodeURL>https://example.com/list-as-genricode.xml</listGenericodeURL>`  to reference genricode files via URLs.

e.g. like this 

```xml
     <codelist>
          <name>codelist-2</name>
          <listURI>https://example.com/page/containing/description/of/list</listURI>
          <listVersion>2.0.3</listVersion>
          <listGenericodeURL>https://example.com/list-as-genricode.xml</listGenericodeURL>
          <term>BT-10</term>
          <value>1</value>
          <value>2</value>
          <value>3</value>
          <value>4</value>          
        </codelist>
```

**Comment by kosek** [comment]
What about using slightly shorter element names more aligned with the rest of the vocabulary:

```` xml
...
<link>https://example.com/page/containing/description/of/list</link>
<version>2.0.3</version>
<genericode>https://example.com/list-as-genricode.xml</genericode>
````

Would this be OK with you?

**Comment by phax** [comment]
In TOOP we're using the GC files directly from within the Schematron like this:
```xml
    <pattern> 
        <let name="countrycodes" value="document('..\codelists\std-gc\CountryIdentificationCode-2.1.gc')//Value[@ColumnRef='code']" />
        <rule context="toop:DCLegalAddress//toop:CountryCode | toop:DPLegalAddress//toop:CountryCode | toop:RoutingInformation//toop:DataConsumerCountryCode | toop:RoutingInformation//toop:DataProviderCountryCode" flag='ERROR' id='gc_check_country_countrycode'> 
            <assert test="$countrycodes//SimpleValue[normalize-space(.) = normalize-space(current()/.)]">The country code must always be specified using the correct code list. Please check <value-of select="name(.)"/>.</assert> 
        </rule> 
    </pattern> 
```
So all the information to do stuff like this would be nice.
Source: https://github.com/TOOP4EU/toop-commons/blob/master/toop-schematron/src/main/resources/140/schematron/TOOP_BusinessRules_DataExchange.sch

**Comment by kosek** [comment]
So shouldn't we add column reference as well so we know against which GC column codelist values should be validated, e.g.

```` xml
...
<link>https://example.com/page/containing/description/of/list</link>
<version>2.0.3</version>
<genericode column="code">https://example.com/list-as-genricode.xml</genericode>
````

**Comment by rkottmann** [comment]
This seems to be a good solution 😄 
 
> ```
> ...
> <link>https://example.com/page/containing/description/of/list</link>
> <version>2.0.3</version>
> <genericode column="code">https://example.com/list-as-genricode.xml</genericode>
> ```
