### ISSUE TITLE
Provide XSD schema for easy validation and authoring of config files

### ISSUE THREAD

**Issue by kosek** [CenPC434/cius-extension-xml#3]

**Comment by kosek** [comment]
I have created simple RELAX NG schema. If something else is needed shout (e.g. re-open this issue).

**Comment by phax** [comment]
Please add XSD so we have better tool support :)
Relax-NG is poorly supported in Java et.al.

**Comment by kosek** [comment]
OK. But let's wait until format is stable. Prototyping in RNC is much faster. I will provide XSD later.

**Comment by phax** [comment]
Hand crafted or jing/trang?

**Comment by kosek** [comment]
Both. First Trang, then multistage XSLT that turned salami slice design of trang into Venetian Blind approach. Then two or three manual tweaks. Once I will have more time I will try to make ant script that does't this automatically and add it into repo.

**Comment by phax** [comment]
*lol* hahaha. Oh shit....
