### ISSUE TITLE
Find a new name for the repository

### ISSUE THREAD

**Issue by phax** [CenPC434/cius-extension-xml#5]
Please change the name `ce-config` to something that is a better understandable.
My proposal is: `cius-extension-template`.
I assume as soon as `cius` is contained, it will be much better to understand

**Comment by kosek** [comment]
Could it be `cius-extension-configuration`? I think that `-template` is confusing, because we are not creating any kind of template but rather describing what can be in invoice.

**Comment by phax** [comment]
Yes sounds okay. What about 'cius-extension-schema'?

**Comment by kosek** [comment]
Naming is the hardest problem. `-schema` could scare some people. ;-)

What about 
`cius-extension-doc` or `cius-extension-documentation` 
or
`cius-extension-def` or `cius-extension-definition`?

**Comment by phax** [comment]
'documentation' gives a wrong impression I guess. 'documentation-schema' would be better ;)
What about '....-declaration'?
Or '....-ruleset'?

**Comment by kosek** [comment]
I can see why German native speakers are proposing names as `cius-extension-documentation-schema` ;-) That's too long for my lazy fingers. At the same time I don't want to introduce new working group for studying differences between "definition" and "declaration".

What about if we drop all suffixes and name repository just simply `cius-extension`? win-win or total failure ;-)

**Comment by phax** [comment]
What about `cius-extension-xml`?
German grammar was the beauty to be able to combine nouns together :-D

**Comment by kosek** [comment]
Yes, I love this on German. I renamed repo as you have suggested. GitHub has created redirect so this shouldn't be creating any issues with dead links.

**Comment by phax** [comment]
The abbreviation "CEX" has room for improvement. "Schema" is better understood in the room here
